python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
ls
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python main.py
python main.py
uv pip install opencv_python
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
git init
git add .
git commit -m "initital setup segmentation"
git add .
git commit -m "initital setup segmentation"
git remote add origin https://github.com/r3dswitch/zenecare.git
git push
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
