python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
ls
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python med_gemma.py 
python main.py
python main.py
uv pip install opencv_python
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
git init
