paths:
  input_path: "/teamspace/studios/this_studio/data/images/0011.png"
  input_directory: "/teamspace/studios/this_studio/data/subset/"
  train_directory: "/teamspace/studios/this_studio/data/subset_gt/"
  test_directory: "/teamspace/studios/this_studio/data/subset_gt/"
  validate_directory: "/teamspace/studios/this_studio/data/labels/"
  output_directory: "/teamspace/studios/this_studio/results"
  output_path: "out.png"
  area_path: "area.png"
  edge_path: "edge.png" 
  bbox_path: "bbox.png"
  compare_path: "compare.png"

tasks:
  bbox_detection:
    model_name: "Owl ViT 2"
    processor: "google/owlv2-base-patch16-ensemble"
    model: "google/owlv2-base-patch16-ensemble"
    prompts: ["Find The Wound in the Image"]
    threshold: 0.2

  segmentation:
    model_name: "Sam 2"
    processor: "facebook/sam-vit-base"
    model: "facebook/sam-vit-base"
    prompts: ["Find The Wound in the Image"]
    threshold: 0.2

envs:
  device: "cpu"

wandb:
  project_id: "wound seg"
